
# Loop constraints
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp CSTEPS_FROM {{. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main CSTEPS_FROM {{. == 2} {.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/acc_tmp:vinit CSTEPS_FROM {{. == 1} {.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW CSTEPS_FROM {{. == 1} {.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL CSTEPS_FROM {{. == 2} {.. == 0}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC CSTEPS_FROM {{. == 16} {.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for CSTEPS_FROM {{. == 6} {.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/for#1 CSTEPS_FROM {{. == 3} {.. == 1}}

# IO operation constraints
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/operator_<11,false>:io_read(widthIn:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/operator_<10,false>:io_read(heightIn:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HCOL:din:io_read(data_in) CSTEPS_FROM {{.. == 0}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/for#1/for#1:io_write(acc) CSTEPS_FROM {{.. == 2}}

# Sync operation constraints

# Real operation constraints
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/acc_tmp:vinit/for:write_mem(acc_tmp:rsc.@) CSTEPS_FROM {{.. == 0}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/acc_tmp:vinit/for:acc CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HCOL:acc CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:acc#9 CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:HACC:acc#2 CSTEPS_FROM {{.. == 3}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:if:acc CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:else:if:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:mux#1 CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:mux#2 CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:mux#1 CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:mux#2 CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::atan_pi_2mi:read_rom(ac_math::atan_pi_pow2_table.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/operator>><33,3,true,AC_TRN,AC_WRAP>:rshift CSTEPS_FROM {{.. == 3}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/operator>><33,3,true,AC_TRN,AC_WRAP>#1:rshift CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:if:acc#3 CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:if:acc CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:if:acc#1 CSTEPS_FROM {{.. == 6}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:if:acc#2 CSTEPS_FROM {{.. == 3}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:else:acc CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:else:acc#1 CSTEPS_FROM {{.. == 6}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:else:acc#2 CSTEPS_FROM {{.. == 3}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:mux CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::atan_pi_2mi#1:read_rom(ac_math::atan_pi_pow2_table.rom_map_1) CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/operator>><33,3,true,AC_TRN,AC_WRAP>#2:rshift CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/operator>><33,3,true,AC_TRN,AC_WRAP>#3:rshift CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:if:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:if:acc CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:if:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:if:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:else:acc CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:else:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:else:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:mux#1 CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:acc CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:acc CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:mux#1 CSTEPS_FROM {{.. == 6}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:mux#2 CSTEPS_FROM {{.. == 3}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:mux CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<45,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:mux#2 CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:acc#5 CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:mul#2 CSTEPS_FROM {{.. == 7}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:acc#6 CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:mul#3 CSTEPS_FROM {{.. == 6}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:acc#7 CSTEPS_FROM {{.. == 8}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:idx:acc CSTEPS_FROM {{.. == 9}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:idx:HACC:idx:acc:conv_2f:acc CSTEPS_FROM {{.. == 10}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:idx:acc#6 CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:idx:acc#4 CSTEPS_FROM {{.. == 11}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:idx:acc#5 CSTEPS_FROM {{.. == 13}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:idx:acc#3 CSTEPS_FROM {{.. == 13}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:read_mem(acc_tmp:rsc.@) CSTEPS_FROM {{.. == 13}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:HACC:acc CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:write_mem(acc_tmp:rsc.@) CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:acc#4 CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HACC/HACC:acc CSTEPS_FROM {{.. == 6}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/operator-<11,false>:acc CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HCOL:equal CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HCOL/HCOL:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/operator-<10,false>:acc CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HROW:equal CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/HROW/HROW:acc CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/for#1/for#1:read_mem(acc_tmp:rsc.@) CSTEPS_FROM {{.. == 0}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/for#1/for#1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/houghTransform/core/core:rlp/main/for#1/for#1:acc CSTEPS_FROM {{.. == 2}}

# Probe constraints

# Loop constraints
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main CSTEPS_FROM {{. == 2} {.. == 0}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE CSTEPS_FROM {{. == 1} {.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE CSTEPS_FROM {{. == 19} {.. == 0}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for CSTEPS_FROM {{. == 6} {.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:for CSTEPS_FROM {{. == 1} {.. == 11}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:for CSTEPS_FROM {{. == 1} {.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:for CSTEPS_FROM {{. == 1} {.. == 11}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:for CSTEPS_FROM {{. == 1} {.. == 15}}

# IO operation constraints
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:acc_in:io_read(acc) CSTEPS_FROM {{.. == 0}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/Hough_Algorithm_HW<1296,864>::getMaxLine:io_write(x1) CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/Hough_Algorithm_HW<1296,864>::getMaxLine:io_write(y1) CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/Hough_Algorithm_HW<1296,864>::getMaxLine:io_write(x2) CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/Hough_Algorithm_HW<1296,864>::getMaxLine:io_write(y2) CSTEPS_FROM {{.. == 1}}

# Sync operation constraints

# Real operation constraints
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator>=<24,16,false,AC_TRN,AC_WRAP,16,false>:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:if:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:if:acc#2 CSTEPS_FROM {{.. == 3}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:if:T_LINE:if:acc CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:acc CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:else:if:acc#1 CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:and CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:mux#1 CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:mux#2 CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:and CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:mux#1 CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:mux#2 CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::atan_pi_2mi:read_rom(ac_math::atan_pi_pow2_table.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/operator>><33,3,true,AC_TRN,AC_WRAP>:rshift CSTEPS_FROM {{.. == 3}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/operator>><33,3,true,AC_TRN,AC_WRAP>#1:rshift CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:if:acc CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:if:acc#1 CSTEPS_FROM {{.. == 6}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:if:acc#2 CSTEPS_FROM {{.. == 3}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:else:acc CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:else:acc#1 CSTEPS_FROM {{.. == 6}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:else:acc#2 CSTEPS_FROM {{.. == 3}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:mux CSTEPS_FROM {{.. == 5}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::atan_pi_2mi#1:read_rom(ac_math::atan_pi_pow2_table.rom_map_1) CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/operator>><33,3,true,AC_TRN,AC_WRAP>#2:rshift CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/operator>><33,3,true,AC_TRN,AC_WRAP>#3:rshift CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:if:acc CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:if:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:if:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:else:acc CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:else:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:else:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:mux#1 CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:acc CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:acc CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:mux#1 CSTEPS_FROM {{.. == 6}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for:mux#2 CSTEPS_FROM {{.. == 3}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:mux CSTEPS_FROM {{.. == 4}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>:for/ac_math::ac_sincos_cordic<27,10,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP>#1:for:mux#2 CSTEPS_FROM {{.. == 2}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:if:acc CSTEPS_FROM {{.. == 6}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:if:aelse:acc CSTEPS_FROM {{.. == 7}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<60,32,true,AC_TRN,AC_WRAP>:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<59,31,true,AC_TRN,AC_WRAP>:acc CSTEPS_FROM {{.. == 8}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:if:if:dividend1:mul CSTEPS_FROM {{.. == 8}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<60,32,true,AC_TRN,AC_WRAP>:acc CSTEPS_FROM {{.. == 10}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:uN:qif:acc CSTEPS_FROM {{.. == 11}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:uN:mux CSTEPS_FROM {{.. == 11}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:uD:qif:acc CSTEPS_FROM {{.. == 8}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:uD:mux CSTEPS_FROM {{.. == 8}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:neg_D:acc CSTEPS_FROM {{.. == 9}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:for:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:for:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:for:acc CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:if#1:acc CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#1:mux CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:else:acc#2 CSTEPS_FROM {{.. == 13}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:else:acc CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#1 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#1 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#2 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#2 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#3 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#3 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#4 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#4 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#5 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#5 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#6 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#6 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#7 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#7 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#8 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#8 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#9 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#9 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#10 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#10 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator+<20,15,true,AC_TRN,AC_WRAP>:acc CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<60,32,true,AC_TRN,AC_WRAP>#1:acc#1 CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<59,31,true,AC_TRN,AC_WRAP>#1:acc CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:if:if:dividend2:mul CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<60,32,true,AC_TRN,AC_WRAP>#1:acc CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:uN:qif:acc CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:uN:mux CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:uD:qif:acc CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:uD:mux CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:neg_D:acc CSTEPS_FROM {{.. == 13}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:for:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:for:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:for:acc CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:if#1:acc CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#3:mux CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:else:acc#2 CSTEPS_FROM {{.. == 17}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:else:acc CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#1 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#1 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#2 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#2 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#3 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#3 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#4 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#4 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#5 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#5 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#6 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#6 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#7 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#7 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#8 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#8 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#9 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#9 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#10 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#10 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator+<20,15,true,AC_TRN,AC_WRAP>#1:acc CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<60,32,true,AC_TRN,AC_WRAP>#2:acc#1 CSTEPS_FROM {{.. == 8}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<58,30,true,AC_TRN,AC_WRAP>:acc CSTEPS_FROM {{.. == 8}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:if:else:dividend1:mul CSTEPS_FROM {{.. == 8}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<60,32,true,AC_TRN,AC_WRAP>#2:acc CSTEPS_FROM {{.. == 10}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:uN:qif:acc CSTEPS_FROM {{.. == 11}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:uN:mux CSTEPS_FROM {{.. == 11}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:uD:qif:acc CSTEPS_FROM {{.. == 8}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:uD:mux CSTEPS_FROM {{.. == 8}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:neg_D:acc CSTEPS_FROM {{.. == 9}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:for:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:for:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:for:acc CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:if#1:acc CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#5:mux CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:else:acc#2 CSTEPS_FROM {{.. == 13}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:else:acc CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#1 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#1 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#2 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#2 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#3 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#3 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#4 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#4 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#5 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#5 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#6 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#6 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#7 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#7 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#8 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#8 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#9 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#9 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#10 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#10 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#11 CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#11 CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator+<20,15,true,AC_TRN,AC_WRAP>#2:acc CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<60,32,true,AC_TRN,AC_WRAP>#3:acc#1 CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<58,30,true,AC_TRN,AC_WRAP>#1:acc CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:if:else:dividend2:mul CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator-<60,32,true,AC_TRN,AC_WRAP>#3:acc CSTEPS_FROM {{.. == 14}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:uN:qif:acc CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:uN:mux CSTEPS_FROM {{.. == 15}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:uD:qif:acc CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:uD:mux CSTEPS_FROM {{.. == 12}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:neg_D:acc CSTEPS_FROM {{.. == 13}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:for:mux#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:for:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:for/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:for:acc CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:if#1:acc CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#7:mux CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:else:acc#2 CSTEPS_FROM {{.. == 17}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:else:acc CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#1 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#1 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#2 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#2 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#3 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#3 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#4 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#4 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#5 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#5 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#6 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#6 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#7 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#7 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#8 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#8 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#9 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#9 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#10 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#10 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#11 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#11 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/operator+<20,15,true,AC_TRN,AC_WRAP>#3:acc CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#33 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#12 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#12 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#34 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#13 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#13 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#35 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#14 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#14 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#36 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#15 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#15 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#37 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#16 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#16 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#38 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#17 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#17 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#39 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#18 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#18 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#40 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:else:mux#19 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#4:mux#19 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#41 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#12 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#12 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#42 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#13 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#13 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#43 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#14 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#14 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#44 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#15 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#15 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#45 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#16 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#16 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#46 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#17 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#17 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#47 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#18 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#18 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#48 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:else:mux#19 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#6:mux#19 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#49 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#11 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#11 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#50 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#12 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#12 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#51 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#13 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#13 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#52 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#14 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#14 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#53 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#15 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#15 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#54 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#16 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#16 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#55 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#17 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#17 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#56 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#18 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#18 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#57 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:else:mux#19 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>:mux#19 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#58 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#11 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#11 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#59 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#12 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#12 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#60 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#13 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#13 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#61 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#14 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#14 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#62 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#15 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#15 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#63 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#16 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#16 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#64 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#17 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#17 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#65 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#18 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#18 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#66 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:else:mux#19 CSTEPS_FROM {{.. == 18}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/ac_math::ac_div<20,15,AC_TRN,AC_WRAP,27,3,AC_TRN,AC_WRAP,20,15,AC_TRN,AC_WRAP>#2:mux#19 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#67 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:if:T_LINE:if:and#34 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#530 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:T_LINE:mux1h CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:if:T_LINE:if:and#35 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:mux#532 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:T_LINE:mux1h#1 CSTEPS_FROM {{.. == 19}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:acc#1 CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/T_LINE/T_LINE:acc CSTEPS_FROM {{.. == 16}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/R_LINE:acc CSTEPS_FROM {{.. == 1}}
directive set /Hough_Algorithm_HW<1296,864>/getMaxLine/core/core:rlp/main/R_LINE/operator<<59,31,true,AC_TRN,AC_WRAP>:acc CSTEPS_FROM {{.. == 1}}

# Probe constraints
